2016-09-14 17:20:05,012 manager INFO 1.1.0
2016-09-14 17:20:05,012 manager INFO Copyright (C) 2003-2010
2016-09-14 17:20:05,012 manager INFO   Noriaki Ando
2016-09-14 17:20:05,013 manager INFO   Intelligent Systems Research Institute, AIST
2016-09-14 17:20:05,013 manager INFO Manager starting.
2016-09-14 17:20:05,013 manager INFO Starting local logging.
2016-09-14 17:20:05,016 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2016-09-14 17:20:07,026 ManagerServant INFO Master manager not found
2016-09-14 17:20:07,029 manager WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2016-09-14 17:20:07,029 LocalServiceAdmin INFO All the local services are enabled.
2016-09-14 17:20:07,039 manager INFO Component type conf file: outTemp.conf loaded.
2016-09-14 17:20:07,045 ec_base INFO setRate(1000000.000000) done
2016-09-14 17:20:07,045 ec_base INFO setRate(1000.000000) done
2016-09-14 17:20:07,046 rtobject INFO 1 execution context was created.
2016-09-14 17:20:07,049 rtobject INFO Initial active configuration set is default-set.
2016-09-14 17:20:14,641 SdoServiceAdmin WARNING No available SDO service in the factory: 
2016-09-14 17:20:14,641 SdoServiceAdmin ERROR type  already exists.
2016-09-14 17:20:14,642 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2016-09-14 17:20:14,642 SdoServiceAdmin ERROR type 5fb71ddc-ec33-488a-ba1d-d6b78fdc2f82 already exists.
2016-09-14 17:21:07,023 ec_base ERROR The component is not responding.
2016-09-14 17:21:07,023 ec_base ERROR Unknown error: Invalid state transition.
2016-09-14 17:22:01,559 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2016-09-14 17:22:01,563 ec_worker WARNING ExecutionContext is already stopped.
2016-09-14 17:22:01,563 ec_base ERROR Invoking on_shutdown() for each RTC failed.
2016-09-14 17:22:01,948 manager ERROR Caught SystemException during root POA destruction
2016-09-14 17:22:01,950 manager ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\Manager.py", line 1673, in shutdownORB
    self._poa.destroy(False, True)
  File "C:\Python27\lib\site-packages\omniORB\PortableServer.py", line 142, in destroy
    self._obj.destroy(etherialize_objects, wait_for_completion)
OBJECT_NOT_EXIST: CORBA.OBJECT_NOT_EXIST(omniORB.OBJECT_NOT_EXIST_POANotInitialised, CORBA.COMPLETED_NO)

